routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Livewire\Volt\Volt;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Volt::route('/', 'orders.index');

app/Models/Executed.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Executed extends Model
{
    protected $table = 'executed';
    protected $fillable = [
        'total_orders',
        'total_cost',
    ];
}

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    public function orderLines()
    {
        return $this->belongsToMany(Product::class, 'orders_lines')->withPivot('qty')->withTimestamps();
    }

    public function getTotalAttribute() {
        return $this->orderLines->map(function ($orderLine) {
            return $orderLine->pivot->qty * $orderLine->cost;
        })->sum();
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/API/ExecutedController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Executed;
use Illuminate\Http\Request;

class ExecutedController extends Controller
{
    public function create(Request $request) {
        $request->validate([
            'total_orders' => ['required', 'integer'],
            'total_cost' => ['required', 'numeric'],
        ]);
        Executed::create($request->only('total_orders', 'total_cost'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

resources/views/livewire/orders/index.blade.php
<?php

use Livewire\Volt\Component;
use App\Models\Executed;

new class extends Component {
    public function with(): array
    {
        return [
            'executed' => Executed::orderBy('id', 'desc')->first(),
        ];
    }
}; ?>

<div>
    <h4>Órdenes de Compra</h4>
    <hr/>
    <livewire:orders.list />
    @if($executed)
        <p>
            Pedidos: {{ $executed->total_orders }} - Total: {{ $executed->total_cost }} - {{ $executed->created_at->format('d/m/Y H:i:s') }}
        </p>
    @endif
</div>

resources/views/livewire/orders/list.blade.php
<?php

use App\Models\Order;
use Livewire\Volt\Component;

new class extends Component {
    public $selectedOrderId;

    public function show($order)
    {
        $this->order = $order;
    }

    public function with(): array
    {
        return [
            'orders' => Order::orderBy('id', 'desc')->paginate(10),
        ];
    }

}; ?>

<div>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Orden</th>
                    <th>Cliente</th>
                    <th class="text-end pe-3">Total</th>
                </tr>
            </head>
            <tbody>
                @foreach($orders as $order)
                <tr>
                    <td>
                        {{ $order->order_ref }}
                    </td>
                    <td>
                        {{ $order->customer_name }}
                    </td>
                    <td class="text-end">
                        <div x-data="{ open: false }">
                            <span x-show="open" x-transition.opacity>
                                <table class="table table-borderless">
                                    <tbody>
                                        @foreach($order->orderLines as $product)
                                        <tr>
                                            <td class="text-end">
                                                {{ $product->name }}
                                            </td>
                                            <td style="width: 60px;">
                                                x {{$product->pivot->qty }}
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </span>
                            <div>
                                $ {{ sprintf("%0.2f", $order->total) }}
                                <button @click="open = !open" class="btn btn-link">
                                    <i class="bi" :class="{'bi-eye' : !open, 'bi-eye-slash' : open}"></i>
                                </button>
                            </div>
                        </div>
                    </td>
                </tr>
                @endforeach

            </tbody>
        </table>
        {{ $orders->links() }}

</div>